apiVersion: v1
kind: page
spec:
  id: es0bqfd
  title: Default page
  content:
    - component: PageRow
      name: pageRow
      children:
        - component: DataGrid
          name: dataGrid
          props:
            rows:
              $$jsExpression: |
                getIncidents.data
            columns:
              - field: id
                type: number
              - field: name
                type: string
                width: 238
              - field: status
                type: string
              - field: species
                type: string
              - field: type
                type: string
              - field: gender
                type: string
              - field: origin
                type: json
              - field: location
                type: json
              - field: image
                type: image
              - field: episode
                type: json
              - field: url
                type: link
              - field: created
                type: string
              - field: actions
                headerName: actions
                type: link
            loading: false
            density: comfortable
            rowIdField: id
            height: 769.9999389648438
    - component: PageRow
      name: pageRow1
      children:
        - component: Button
          name: button
  display: shell
  queries:
    - name: getIncidents
      query:
        kind: rest
        url: https://rickandmortyapi.com/api/character
        headers: []
        method: GET
        transform: return data.results;
        transformEnabled: true
